variable "distro" {}
variable "ssh_key" {}
variable "vm_count" {}
variable "vm_subnet" {}
variable "vm_starting_ip" {}
variable "n_cores_per_vm" {}
variable "memory_per_vm" {}
variable "vm_disk_size" {}
variable "network_domain" {}
variable "proxmox_n_sockets_per_vm" {}
variable "proxmox_endpoint" {}
variable "proxmox_api_token" {}
variable "proxmox_ssh_agent_username" {}
variable "proxmox_target_node_name" {}
variable "proxmox_template_id" {}
variable "proxmox_VM_id_start" {}
variable "proxmox_vm_tag" {}
variable "proxmox_config_datastore_id" {}
variable "proxmox_vm_datastore_id" {}
variable "proxmox_network_bridge_name" {}
variable "proxmox_network_interface_model" {}
variable "proxmox_vm_disk_interface" {}
